/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.lexer;

import java.io.*;
import cida.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCode(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTipoNumber(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTipoAnswer(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTipoSymbol(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParenteseE(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParenteseD(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColcheteE(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColcheteD(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenos(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMais(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMultiplicacao(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDivisao(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TModulo(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribuicao(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgualdade(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiferente(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorIgual(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorIgual(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenor(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaior(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNegacao(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnd(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOr(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TXor(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAs(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLong(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIn(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCase(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThat(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConsidering(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFrom(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTo(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBy(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDo(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUnalterable(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAlterable(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVector(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicio(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFim(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCapture(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TShow(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TYes(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNo(line, pos); }
    Token new45(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSymbol(text, line, pos); }
    Token new46(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSymbolVector(text, line, pos); }
    Token new47(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioBloco(text, line, pos); }
    Token new48(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioLinha(text, line, pos); }
    Token new49(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(text, line, pos); }
    Token new50(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new51(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVazio(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {37, 37, 7}, {39, 39, 8}, {40, 40, 9}, {41, 41, 10}, {42, 42, 11}, {43, 43, 12}, {44, 44, 13}, {45, 45, 14}, {46, 46, 15}, {47, 47, 16}, {48, 57, 17}, {60, 60, 18}, {61, 61, 19}, {62, 62, 20}, {65, 90, 21}, {91, 91, 22}, {93, 93, 23}, {97, 97, 24}, {98, 98, 25}, {99, 99, 26}, {100, 100, 27}, {101, 101, 21}, {102, 102, 28}, {103, 104, 21}, {105, 105, 29}, {106, 107, 21}, {108, 108, 30}, {109, 109, 21}, {110, 110, 31}, {111, 111, 32}, {112, 114, 21}, {115, 115, 33}, {116, 116, 34}, {117, 117, 35}, {118, 118, 36}, {119, 119, 21}, {120, 120, 37}, {121, 121, 38}, {122, 122, 21}, {123, 123, 39}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 40}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {{61, 61, 41}, },
            {{0, 33, 42}, {34, 34, 43}, {35, 91, 42}, {92, 92, 44}, {93, 65535, 42}, },
            {},
            {{0, 38, 45}, {40, 91, 45}, {92, 92, 46}, {93, 65535, 45}, },
            {},
            {},
            {},
            {},
            {},
            {{45, 45, 47}, },
            {},
            {},
            {{46, 46, 48}, {48, 57, 17}, },
            {{60, 60, 49}, {61, 61, 50}, },
            {{61, 61, 51}, },
            {{61, 61, 52}, },
            {{65, 90, 21}, {97, 122, 21}, },
            {},
            {},
            {{65, 90, 21}, {97, 107, 21}, {108, 108, 53}, {109, 109, 21}, {110, 110, 54}, {111, 114, 21}, {115, 115, 55}, {116, 122, 21}, },
            {{65, 90, 21}, {97, 120, 21}, {121, 121, 56}, {122, 122, 21}, },
            {{65, 90, 21}, {97, 97, 57}, {98, 110, 21}, {111, 111, 58}, {112, 122, 21}, },
            {{65, 90, 21}, {97, 110, 21}, {111, 111, 59}, {112, 122, 21}, },
            {{65, 90, 21}, {97, 104, 21}, {105, 105, 60}, {106, 113, 21}, {114, 114, 61}, {115, 122, 21}, },
            {{65, 90, 21}, {97, 109, 21}, {110, 110, 62}, {111, 122, 21}, },
            {{65, 110, -29}, {111, 111, 63}, {112, 122, 21}, },
            {{65, 110, -29}, {111, 111, 64}, {112, 116, 21}, {117, 117, 65}, {118, 122, 21}, },
            {{65, 90, 21}, {97, 113, 21}, {114, 114, 66}, {115, 122, 21}, },
            {{65, 90, 21}, {97, 103, 21}, {104, 104, 67}, {105, 115, 21}, {116, 116, 68}, {117, 120, 21}, {121, 121, 69}, {122, 122, 21}, },
            {{65, 103, -35}, {104, 104, 70}, {105, 110, 21}, {111, 111, 71}, {112, 122, 21}, },
            {{65, 109, -31}, {110, 110, 72}, {111, 122, 21}, },
            {{65, 90, 21}, {97, 100, 21}, {101, 101, 73}, {102, 122, 21}, },
            {{65, 110, -29}, {111, 111, 74}, {112, 122, 21}, },
            {{65, 100, -38}, {101, 101, 75}, {102, 122, 21}, },
            {{45, 45, 76}, },
            {{9, 32, -2}, },
            {},
            {{0, 65535, -8}, },
            {},
            {{0, 33, 42}, {34, 34, 77}, {35, 38, 42}, {39, 39, 78}, {40, 47, 42}, {48, 48, 79}, {49, 91, 42}, {92, 92, 80}, {93, 96, 42}, {97, 97, 81}, {98, 98, 82}, {99, 101, 42}, {102, 102, 83}, {103, 109, 42}, {110, 110, 84}, {111, 113, 42}, {114, 114, 85}, {115, 115, 42}, {116, 116, 86}, {117, 117, 42}, {118, 118, 87}, {119, 65535, 42}, },
            {{39, 39, 88}, },
            {{34, 34, 89}, {39, 39, 90}, {48, 48, 91}, {92, 92, 92}, {97, 97, 93}, {98, 98, 94}, {102, 102, 95}, {110, 110, 96}, {114, 114, 97}, {116, 116, 98}, {118, 118, 99}, },
            {{10, 10, 100}, {13, 13, 101}, {32, 32, 102}, {48, 57, 103}, {65, 90, 104}, {97, 122, 104}, },
            {{48, 57, 105}, },
            {},
            {},
            {},
            {},
            {{65, 90, 21}, {97, 115, 21}, {116, 116, 106}, {117, 122, 21}, },
            {{65, 90, 21}, {97, 99, 21}, {100, 100, 107}, {101, 114, 21}, {115, 115, 108}, {116, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 122, -23}, },
            {{65, 90, 21}, {97, 111, 21}, {112, 112, 109}, {113, 114, 21}, {115, 115, 110}, {116, 122, 21}, },
            {{65, 99, -56}, {100, 100, 111}, {101, 109, 21}, {110, 110, 112}, {111, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 109, -31}, {110, 110, 113}, {111, 122, 21}, },
            {{65, 110, -29}, {111, 111, 114}, {112, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 109, -31}, {110, 110, 115}, {111, 122, 21}, },
            {{65, 115, -55}, {116, 116, 116}, {117, 122, 21}, },
            {{65, 90, 21}, {97, 108, 21}, {109, 109, 117}, {110, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 110, -29}, {111, 111, 118}, {112, 122, 21}, },
            {{65, 90, 21}, {97, 97, 119}, {98, 122, 21}, },
            {{65, 108, -67}, {109, 109, 120}, {110, 122, 21}, },
            {{65, 90, 21}, {97, 97, 121}, {98, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 90, 21}, {97, 97, 122}, {98, 122, 21}, },
            {{65, 90, 21}, {97, 98, 21}, {99, 99, 123}, {100, 122, 21}, },
            {{65, 113, -34}, {114, 114, 124}, {115, 122, 21}, },
            {{65, 90, 21}, {97, 114, 21}, {115, 115, 125}, {116, 122, 21}, },
            {{0, 44, 126}, {45, 45, 127}, {46, 65535, 126}, },
            {{0, 65535, -8}, },
            {{0, 65535, -8}, },
            {{0, 65535, -8}, },
            {{0, 65535, -46}, },
            {{0, 65535, -8}, },
            {{0, 65535, -8}, },
            {{0, 65535, -8}, },
            {{0, 65535, -8}, },
            {{0, 65535, -8}, },
            {{0, 65535, -8}, },
            {{0, 65535, -8}, },
            {},
            {{39, 39, 88}, },
            {{39, 39, 88}, },
            {{39, 39, 88}, },
            {{39, 39, 88}, },
            {{39, 39, 88}, },
            {{39, 39, 88}, },
            {{39, 39, 88}, },
            {{39, 39, 88}, },
            {{39, 39, 88}, },
            {{39, 39, 88}, },
            {{39, 39, 88}, },
            {},
            {{10, 10, 128}, },
            {{10, 122, -49}, },
            {{10, 122, -49}, },
            {{10, 122, -49}, },
            {{48, 57, 105}, },
            {{65, 100, -38}, {101, 101, 129}, {102, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 90, 21}, {97, 118, 21}, {119, 119, 130}, {120, 122, 21}, },
            {{65, 115, -55}, {116, 116, 131}, {117, 122, 21}, },
            {{65, 100, -38}, {101, 101, 132}, {102, 122, 21}, },
            {{65, 100, -38}, {101, 101, 133}, {102, 122, 21}, },
            {{65, 114, -77}, {115, 115, 134}, {116, 122, 21}, },
            {{65, 104, -30}, {105, 105, 135}, {106, 122, 21}, },
            {{65, 108, -67}, {109, 109, 136}, {110, 122, 21}, },
            {{65, 90, 21}, {97, 102, 21}, {103, 103, 137}, {104, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 90, 21}, {97, 97, 21}, {98, 98, 138}, {99, 122, 21}, },
            {{65, 118, -110}, {119, 119, 139}, {120, 122, 21}, },
            {{65, 113, -34}, {114, 114, 140}, {115, 122, 21}, },
            {{65, 97, -119}, {98, 98, 141}, {99, 122, 21}, },
            {{65, 115, -55}, {116, 116, 142}, {117, 122, 21}, },
            {{65, 107, -26}, {108, 108, 143}, {109, 122, 21}, },
            {{65, 115, -55}, {116, 116, 144}, {117, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 122, -23}, },
            {{0, 65535, -78}, },
            {{0, 45, -78}, {46, 124, 126}, {125, 125, 145}, {126, 65535, 126}, },
            {},
            {{65, 113, -34}, {114, 114, 146}, {115, 122, 21}, },
            {{65, 100, -38}, {101, 101, 147}, {102, 122, 21}, },
            {{65, 90, 21}, {97, 116, 21}, {117, 117, 148}, {118, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 122, -23}, },
            {{65, 104, -30}, {105, 105, 149}, {106, 122, 21}, },
            {{65, 114, -77}, {115, 115, 150}, {116, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 122, -23}, },
            {{65, 100, -38}, {101, 101, 151}, {102, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 115, -55}, {116, 116, 152}, {117, 122, 21}, },
            {{65, 110, -29}, {111, 111, 153}, {112, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 115, -55}, {116, 116, 154}, {117, 122, 21}, },
            {{65, 110, -29}, {111, 111, 155}, {112, 122, 21}, },
            {{0, 65535, -78}, },
            {{65, 90, 21}, {97, 97, 156}, {98, 122, 21}, },
            {{65, 113, -34}, {114, 114, 157}, {115, 122, 21}, },
            {{65, 113, -34}, {114, 114, 158}, {115, 122, 21}, },
            {{65, 99, -56}, {100, 100, 159}, {101, 122, 21}, },
            {{65, 103, -35}, {104, 104, 160}, {105, 122, 21}, },
            {{65, 113, -34}, {114, 114, 161}, {115, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 107, -26}, {108, 108, 162}, {109, 122, 21}, },
            {{65, 100, -38}, {101, 101, 163}, {102, 122, 21}, },
            {{65, 113, -34}, {114, 114, 164}, {115, 122, 21}, },
            {{65, 97, -119}, {98, 98, 165}, {99, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 100, -38}, {101, 101, 166}, {102, 122, 21}, },
            {{65, 100, -38}, {101, 101, 167}, {102, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 122, -23}, },
            {{65, 122, -23}, },
            {{65, 113, -34}, {114, 114, 168}, {115, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 107, -26}, {108, 108, 169}, {109, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 113, -34}, {114, 114, 170}, {115, 122, 21}, },
            {{65, 90, 21}, {97, 97, 171}, {98, 122, 21}, },
            {{65, 100, -38}, {101, 101, 172}, {102, 122, 21}, },
            {{65, 104, -30}, {105, 105, 173}, {106, 122, 21}, },
            {{65, 97, -119}, {98, 98, 174}, {99, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 109, -31}, {110, 110, 175}, {111, 122, 21}, },
            {{65, 107, -26}, {108, 108, 176}, {109, 122, 21}, },
            {{65, 102, -117}, {103, 103, 177}, {104, 122, 21}, },
            {{65, 100, -38}, {101, 101, 178}, {102, 122, 21}, },
            {{65, 122, -23}, },
            {{65, 122, -23}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 51, 51, 51, 51, -1, -1, 14, -1, 6, 7, 12, 11, 1, 10, 0, 13, 49, 20, -1, 21, 50, 8, 9, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, -1, 51, 17, -1, 46, -1, -1, -1, -1, -1, 15, 18, 16, 19, 50, 50, 26, 34, 50, 50, 35, 50, 50, 28, 50, 44, 50, 24, 50, 50, 50, 50, 33, 50, 50, 50, 50, -1, 46, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 45, -1, 45, -1, -1, -1, -1, -1, -1, -1, -1, -1, 48, 48, -1, -1, -1, 49, 50, 23, 50, 50, 50, 50, 50, 50, 50, 50, 22, 50, 50, 50, 50, 50, 50, 50, 25, 43, -1, -1, 48, 50, 50, 50, 29, 2, 50, 50, 32, 27, 50, 42, 50, 50, 30, 50, 50, 47, 50, 50, 50, 50, 50, 50, 39, 50, 50, 50, 50, 4, 50, 50, 40, 3, 5, 50, 38, 50, 41, 50, 50, 50, 50, 50, 37, 50, 50, 50, 50, 31, 36, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
