/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AAnswerTipoBase extends PTipoBase
{
    private TTipoAnswer _tipoAnswer_;

    public AAnswerTipoBase()
    {
        // Constructor
    }

    public AAnswerTipoBase(
        @SuppressWarnings("hiding") TTipoAnswer _tipoAnswer_)
    {
        // Constructor
        setTipoAnswer(_tipoAnswer_);

    }

    @Override
    public Object clone()
    {
        return new AAnswerTipoBase(
            cloneNode(this._tipoAnswer_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAnswerTipoBase(this);
    }

    public TTipoAnswer getTipoAnswer()
    {
        return this._tipoAnswer_;
    }

    public void setTipoAnswer(TTipoAnswer node)
    {
        if(this._tipoAnswer_ != null)
        {
            this._tipoAnswer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoAnswer_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoAnswer_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoAnswer_ == child)
        {
            this._tipoAnswer_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoAnswer_ == oldChild)
        {
            setTipoAnswer((TTipoAnswer) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
