/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class ADiferenteExprDiferente extends PExprDiferente
{
    private PExprDiferente _exprDiferente_;
    private TDiferente _diferente_;
    private PExprMatematica _exprMatematica_;

    public ADiferenteExprDiferente()
    {
        // Constructor
    }

    public ADiferenteExprDiferente(
        @SuppressWarnings("hiding") PExprDiferente _exprDiferente_,
        @SuppressWarnings("hiding") TDiferente _diferente_,
        @SuppressWarnings("hiding") PExprMatematica _exprMatematica_)
    {
        // Constructor
        setExprDiferente(_exprDiferente_);

        setDiferente(_diferente_);

        setExprMatematica(_exprMatematica_);

    }

    @Override
    public Object clone()
    {
        return new ADiferenteExprDiferente(
            cloneNode(this._exprDiferente_),
            cloneNode(this._diferente_),
            cloneNode(this._exprMatematica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADiferenteExprDiferente(this);
    }

    public PExprDiferente getExprDiferente()
    {
        return this._exprDiferente_;
    }

    public void setExprDiferente(PExprDiferente node)
    {
        if(this._exprDiferente_ != null)
        {
            this._exprDiferente_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprDiferente_ = node;
    }

    public TDiferente getDiferente()
    {
        return this._diferente_;
    }

    public void setDiferente(TDiferente node)
    {
        if(this._diferente_ != null)
        {
            this._diferente_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._diferente_ = node;
    }

    public PExprMatematica getExprMatematica()
    {
        return this._exprMatematica_;
    }

    public void setExprMatematica(PExprMatematica node)
    {
        if(this._exprMatematica_ != null)
        {
            this._exprMatematica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMatematica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprDiferente_)
            + toString(this._diferente_)
            + toString(this._exprMatematica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprDiferente_ == child)
        {
            this._exprDiferente_ = null;
            return;
        }

        if(this._diferente_ == child)
        {
            this._diferente_ = null;
            return;
        }

        if(this._exprMatematica_ == child)
        {
            this._exprMatematica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprDiferente_ == oldChild)
        {
            setExprDiferente((PExprDiferente) newChild);
            return;
        }

        if(this._diferente_ == oldChild)
        {
            setDiferente((TDiferente) newChild);
            return;
        }

        if(this._exprMatematica_ == oldChild)
        {
            setExprMatematica((PExprMatematica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
