/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class ADivisaoFator extends PFator
{
    private PFator _fator_;
    private TDivisao _divisao_;
    private PExprNegativo _exprNegativo_;

    public ADivisaoFator()
    {
        // Constructor
    }

    public ADivisaoFator(
        @SuppressWarnings("hiding") PFator _fator_,
        @SuppressWarnings("hiding") TDivisao _divisao_,
        @SuppressWarnings("hiding") PExprNegativo _exprNegativo_)
    {
        // Constructor
        setFator(_fator_);

        setDivisao(_divisao_);

        setExprNegativo(_exprNegativo_);

    }

    @Override
    public Object clone()
    {
        return new ADivisaoFator(
            cloneNode(this._fator_),
            cloneNode(this._divisao_),
            cloneNode(this._exprNegativo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivisaoFator(this);
    }

    public PFator getFator()
    {
        return this._fator_;
    }

    public void setFator(PFator node)
    {
        if(this._fator_ != null)
        {
            this._fator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fator_ = node;
    }

    public TDivisao getDivisao()
    {
        return this._divisao_;
    }

    public void setDivisao(TDivisao node)
    {
        if(this._divisao_ != null)
        {
            this._divisao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._divisao_ = node;
    }

    public PExprNegativo getExprNegativo()
    {
        return this._exprNegativo_;
    }

    public void setExprNegativo(PExprNegativo node)
    {
        if(this._exprNegativo_ != null)
        {
            this._exprNegativo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNegativo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fator_)
            + toString(this._divisao_)
            + toString(this._exprNegativo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fator_ == child)
        {
            this._fator_ = null;
            return;
        }

        if(this._divisao_ == child)
        {
            this._divisao_ = null;
            return;
        }

        if(this._exprNegativo_ == child)
        {
            this._exprNegativo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fator_ == oldChild)
        {
            setFator((PFator) newChild);
            return;
        }

        if(this._divisao_ == oldChild)
        {
            setDivisao((TDivisao) newChild);
            return;
        }

        if(this._exprNegativo_ == oldChild)
        {
            setExprNegativo((PExprNegativo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
