/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AExprMatematicaExprDiferente extends PExprDiferente
{
    private PExprMatematica _exprMatematica_;

    public AExprMatematicaExprDiferente()
    {
        // Constructor
    }

    public AExprMatematicaExprDiferente(
        @SuppressWarnings("hiding") PExprMatematica _exprMatematica_)
    {
        // Constructor
        setExprMatematica(_exprMatematica_);

    }

    @Override
    public Object clone()
    {
        return new AExprMatematicaExprDiferente(
            cloneNode(this._exprMatematica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprMatematicaExprDiferente(this);
    }

    public PExprMatematica getExprMatematica()
    {
        return this._exprMatematica_;
    }

    public void setExprMatematica(PExprMatematica node)
    {
        if(this._exprMatematica_ != null)
        {
            this._exprMatematica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMatematica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprMatematica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprMatematica_ == child)
        {
            this._exprMatematica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprMatematica_ == oldChild)
        {
            setExprMatematica((PExprMatematica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
