/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AExprNegacaoExprAnd extends PExprAnd
{
    private PExprNegacao _exprNegacao_;

    public AExprNegacaoExprAnd()
    {
        // Constructor
    }

    public AExprNegacaoExprAnd(
        @SuppressWarnings("hiding") PExprNegacao _exprNegacao_)
    {
        // Constructor
        setExprNegacao(_exprNegacao_);

    }

    @Override
    public Object clone()
    {
        return new AExprNegacaoExprAnd(
            cloneNode(this._exprNegacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprNegacaoExprAnd(this);
    }

    public PExprNegacao getExprNegacao()
    {
        return this._exprNegacao_;
    }

    public void setExprNegacao(PExprNegacao node)
    {
        if(this._exprNegacao_ != null)
        {
            this._exprNegacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNegacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprNegacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprNegacao_ == child)
        {
            this._exprNegacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprNegacao_ == oldChild)
        {
            setExprNegacao((PExprNegacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
