/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AExprMaiorExprMaiorIgual extends PExprMaiorIgual
{
    private PExprMaior _exprMaior_;

    public AExprMaiorExprMaiorIgual()
    {
        // Constructor
    }

    public AExprMaiorExprMaiorIgual(
        @SuppressWarnings("hiding") PExprMaior _exprMaior_)
    {
        // Constructor
        setExprMaior(_exprMaior_);

    }

    @Override
    public Object clone()
    {
        return new AExprMaiorExprMaiorIgual(
            cloneNode(this._exprMaior_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprMaiorExprMaiorIgual(this);
    }

    public PExprMaior getExprMaior()
    {
        return this._exprMaior_;
    }

    public void setExprMaior(PExprMaior node)
    {
        if(this._exprMaior_ != null)
        {
            this._exprMaior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMaior_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprMaior_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprMaior_ == child)
        {
            this._exprMaior_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprMaior_ == oldChild)
        {
            setExprMaior((PExprMaior) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
