/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AExprOrExpr extends PExpr
{
    private PExprOr _exprOr_;

    public AExprOrExpr()
    {
        // Constructor
    }

    public AExprOrExpr(
        @SuppressWarnings("hiding") PExprOr _exprOr_)
    {
        // Constructor
        setExprOr(_exprOr_);

    }

    @Override
    public Object clone()
    {
        return new AExprOrExpr(
            cloneNode(this._exprOr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprOrExpr(this);
    }

    public PExprOr getExprOr()
    {
        return this._exprOr_;
    }

    public void setExprOr(PExprOr node)
    {
        if(this._exprOr_ != null)
        {
            this._exprOr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprOr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprOr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprOr_ == child)
        {
            this._exprOr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprOr_ == oldChild)
        {
            setExprOr((PExprOr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
