/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AExprMenorExprMaior extends PExprMaior
{
    private PExprMenor _exprMenor_;

    public AExprMenorExprMaior()
    {
        // Constructor
    }

    public AExprMenorExprMaior(
        @SuppressWarnings("hiding") PExprMenor _exprMenor_)
    {
        // Constructor
        setExprMenor(_exprMenor_);

    }

    @Override
    public Object clone()
    {
        return new AExprMenorExprMaior(
            cloneNode(this._exprMenor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprMenorExprMaior(this);
    }

    public PExprMenor getExprMenor()
    {
        return this._exprMenor_;
    }

    public void setExprMenor(PExprMenor node)
    {
        if(this._exprMenor_ != null)
        {
            this._exprMenor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMenor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprMenor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprMenor_ == child)
        {
            this._exprMenor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprMenor_ == oldChild)
        {
            setExprMenor((PExprMenor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
