/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AExprAndExprOr extends PExprOr
{
    private PExprAnd _exprAnd_;

    public AExprAndExprOr()
    {
        // Constructor
    }

    public AExprAndExprOr(
        @SuppressWarnings("hiding") PExprAnd _exprAnd_)
    {
        // Constructor
        setExprAnd(_exprAnd_);

    }

    @Override
    public Object clone()
    {
        return new AExprAndExprOr(
            cloneNode(this._exprAnd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprAndExprOr(this);
    }

    public PExprAnd getExprAnd()
    {
        return this._exprAnd_;
    }

    public void setExprAnd(PExprAnd node)
    {
        if(this._exprAnd_ != null)
        {
            this._exprAnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprAnd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprAnd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprAnd_ == child)
        {
            this._exprAnd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprAnd_ == oldChild)
        {
            setExprAnd((PExprAnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
