/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AExprMaiorIgualExprIgualdade extends PExprIgualdade
{
    private PExprMaiorIgual _exprMaiorIgual_;

    public AExprMaiorIgualExprIgualdade()
    {
        // Constructor
    }

    public AExprMaiorIgualExprIgualdade(
        @SuppressWarnings("hiding") PExprMaiorIgual _exprMaiorIgual_)
    {
        // Constructor
        setExprMaiorIgual(_exprMaiorIgual_);

    }

    @Override
    public Object clone()
    {
        return new AExprMaiorIgualExprIgualdade(
            cloneNode(this._exprMaiorIgual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprMaiorIgualExprIgualdade(this);
    }

    public PExprMaiorIgual getExprMaiorIgual()
    {
        return this._exprMaiorIgual_;
    }

    public void setExprMaiorIgual(PExprMaiorIgual node)
    {
        if(this._exprMaiorIgual_ != null)
        {
            this._exprMaiorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMaiorIgual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprMaiorIgual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprMaiorIgual_ == child)
        {
            this._exprMaiorIgual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprMaiorIgual_ == oldChild)
        {
            setExprMaiorIgual((PExprMaiorIgual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
