/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AExprDiferenteExprMenorIgual extends PExprMenorIgual
{
    private PExprDiferente _exprDiferente_;

    public AExprDiferenteExprMenorIgual()
    {
        // Constructor
    }

    public AExprDiferenteExprMenorIgual(
        @SuppressWarnings("hiding") PExprDiferente _exprDiferente_)
    {
        // Constructor
        setExprDiferente(_exprDiferente_);

    }

    @Override
    public Object clone()
    {
        return new AExprDiferenteExprMenorIgual(
            cloneNode(this._exprDiferente_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprDiferenteExprMenorIgual(this);
    }

    public PExprDiferente getExprDiferente()
    {
        return this._exprDiferente_;
    }

    public void setExprDiferente(PExprDiferente node)
    {
        if(this._exprDiferente_ != null)
        {
            this._exprDiferente_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprDiferente_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprDiferente_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprDiferente_ == child)
        {
            this._exprDiferente_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprDiferente_ == oldChild)
        {
            setExprDiferente((PExprDiferente) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
