/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AExprIgualdadeExprNegacao extends PExprNegacao
{
    private PExprIgualdade _exprIgualdade_;

    public AExprIgualdadeExprNegacao()
    {
        // Constructor
    }

    public AExprIgualdadeExprNegacao(
        @SuppressWarnings("hiding") PExprIgualdade _exprIgualdade_)
    {
        // Constructor
        setExprIgualdade(_exprIgualdade_);

    }

    @Override
    public Object clone()
    {
        return new AExprIgualdadeExprNegacao(
            cloneNode(this._exprIgualdade_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprIgualdadeExprNegacao(this);
    }

    public PExprIgualdade getExprIgualdade()
    {
        return this._exprIgualdade_;
    }

    public void setExprIgualdade(PExprIgualdade node)
    {
        if(this._exprIgualdade_ != null)
        {
            this._exprIgualdade_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprIgualdade_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprIgualdade_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprIgualdade_ == child)
        {
            this._exprIgualdade_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprIgualdade_ == oldChild)
        {
            setExprIgualdade((PExprIgualdade) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
