/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AIgualdadeExprIgualdade extends PExprIgualdade
{
    private PExprIgualdade _exprIgualdade_;
    private TIgualdade _igualdade_;
    private PExprMaiorIgual _exprMaiorIgual_;

    public AIgualdadeExprIgualdade()
    {
        // Constructor
    }

    public AIgualdadeExprIgualdade(
        @SuppressWarnings("hiding") PExprIgualdade _exprIgualdade_,
        @SuppressWarnings("hiding") TIgualdade _igualdade_,
        @SuppressWarnings("hiding") PExprMaiorIgual _exprMaiorIgual_)
    {
        // Constructor
        setExprIgualdade(_exprIgualdade_);

        setIgualdade(_igualdade_);

        setExprMaiorIgual(_exprMaiorIgual_);

    }

    @Override
    public Object clone()
    {
        return new AIgualdadeExprIgualdade(
            cloneNode(this._exprIgualdade_),
            cloneNode(this._igualdade_),
            cloneNode(this._exprMaiorIgual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIgualdadeExprIgualdade(this);
    }

    public PExprIgualdade getExprIgualdade()
    {
        return this._exprIgualdade_;
    }

    public void setExprIgualdade(PExprIgualdade node)
    {
        if(this._exprIgualdade_ != null)
        {
            this._exprIgualdade_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprIgualdade_ = node;
    }

    public TIgualdade getIgualdade()
    {
        return this._igualdade_;
    }

    public void setIgualdade(TIgualdade node)
    {
        if(this._igualdade_ != null)
        {
            this._igualdade_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._igualdade_ = node;
    }

    public PExprMaiorIgual getExprMaiorIgual()
    {
        return this._exprMaiorIgual_;
    }

    public void setExprMaiorIgual(PExprMaiorIgual node)
    {
        if(this._exprMaiorIgual_ != null)
        {
            this._exprMaiorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMaiorIgual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprIgualdade_)
            + toString(this._igualdade_)
            + toString(this._exprMaiorIgual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprIgualdade_ == child)
        {
            this._exprIgualdade_ = null;
            return;
        }

        if(this._igualdade_ == child)
        {
            this._igualdade_ = null;
            return;
        }

        if(this._exprMaiorIgual_ == child)
        {
            this._exprMaiorIgual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprIgualdade_ == oldChild)
        {
            setExprIgualdade((PExprIgualdade) newChild);
            return;
        }

        if(this._igualdade_ == oldChild)
        {
            setIgualdade((TIgualdade) newChild);
            return;
        }

        if(this._exprMaiorIgual_ == oldChild)
        {
            setExprMaiorIgual((PExprMaiorIgual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
