/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorExprMaior extends PExprMaior
{
    private PExprMaior _exprMaior_;
    private TMaior _maior_;
    private PExprMenor _exprMenor_;

    public AMaiorExprMaior()
    {
        // Constructor
    }

    public AMaiorExprMaior(
        @SuppressWarnings("hiding") PExprMaior _exprMaior_,
        @SuppressWarnings("hiding") TMaior _maior_,
        @SuppressWarnings("hiding") PExprMenor _exprMenor_)
    {
        // Constructor
        setExprMaior(_exprMaior_);

        setMaior(_maior_);

        setExprMenor(_exprMenor_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorExprMaior(
            cloneNode(this._exprMaior_),
            cloneNode(this._maior_),
            cloneNode(this._exprMenor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorExprMaior(this);
    }

    public PExprMaior getExprMaior()
    {
        return this._exprMaior_;
    }

    public void setExprMaior(PExprMaior node)
    {
        if(this._exprMaior_ != null)
        {
            this._exprMaior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMaior_ = node;
    }

    public TMaior getMaior()
    {
        return this._maior_;
    }

    public void setMaior(TMaior node)
    {
        if(this._maior_ != null)
        {
            this._maior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maior_ = node;
    }

    public PExprMenor getExprMenor()
    {
        return this._exprMenor_;
    }

    public void setExprMenor(PExprMenor node)
    {
        if(this._exprMenor_ != null)
        {
            this._exprMenor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMenor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprMaior_)
            + toString(this._maior_)
            + toString(this._exprMenor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprMaior_ == child)
        {
            this._exprMaior_ = null;
            return;
        }

        if(this._maior_ == child)
        {
            this._maior_ = null;
            return;
        }

        if(this._exprMenor_ == child)
        {
            this._exprMenor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprMaior_ == oldChild)
        {
            setExprMaior((PExprMaior) newChild);
            return;
        }

        if(this._maior_ == oldChild)
        {
            setMaior((TMaior) newChild);
            return;
        }

        if(this._exprMenor_ == oldChild)
        {
            setExprMenor((PExprMenor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
