/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AMenorExprMenor extends PExprMenor
{
    private PExprMenor _exprMenor_;
    private TMenor _menor_;
    private PExprMenorIgual _exprMenorIgual_;

    public AMenorExprMenor()
    {
        // Constructor
    }

    public AMenorExprMenor(
        @SuppressWarnings("hiding") PExprMenor _exprMenor_,
        @SuppressWarnings("hiding") TMenor _menor_,
        @SuppressWarnings("hiding") PExprMenorIgual _exprMenorIgual_)
    {
        // Constructor
        setExprMenor(_exprMenor_);

        setMenor(_menor_);

        setExprMenorIgual(_exprMenorIgual_);

    }

    @Override
    public Object clone()
    {
        return new AMenorExprMenor(
            cloneNode(this._exprMenor_),
            cloneNode(this._menor_),
            cloneNode(this._exprMenorIgual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorExprMenor(this);
    }

    public PExprMenor getExprMenor()
    {
        return this._exprMenor_;
    }

    public void setExprMenor(PExprMenor node)
    {
        if(this._exprMenor_ != null)
        {
            this._exprMenor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMenor_ = node;
    }

    public TMenor getMenor()
    {
        return this._menor_;
    }

    public void setMenor(TMenor node)
    {
        if(this._menor_ != null)
        {
            this._menor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menor_ = node;
    }

    public PExprMenorIgual getExprMenorIgual()
    {
        return this._exprMenorIgual_;
    }

    public void setExprMenorIgual(PExprMenorIgual node)
    {
        if(this._exprMenorIgual_ != null)
        {
            this._exprMenorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMenorIgual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprMenor_)
            + toString(this._menor_)
            + toString(this._exprMenorIgual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprMenor_ == child)
        {
            this._exprMenor_ = null;
            return;
        }

        if(this._menor_ == child)
        {
            this._menor_ = null;
            return;
        }

        if(this._exprMenorIgual_ == child)
        {
            this._exprMenorIgual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprMenor_ == oldChild)
        {
            setExprMenor((PExprMenor) newChild);
            return;
        }

        if(this._menor_ == oldChild)
        {
            setMenor((TMenor) newChild);
            return;
        }

        if(this._exprMenorIgual_ == oldChild)
        {
            setExprMenorIgual((PExprMenorIgual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
