/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class ANegativoExprNegativo extends PExprNegativo
{
    private TMenos _menos_;
    private PExprNegativo _exprNegativo_;

    public ANegativoExprNegativo()
    {
        // Constructor
    }

    public ANegativoExprNegativo(
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PExprNegativo _exprNegativo_)
    {
        // Constructor
        setMenos(_menos_);

        setExprNegativo(_exprNegativo_);

    }

    @Override
    public Object clone()
    {
        return new ANegativoExprNegativo(
            cloneNode(this._menos_),
            cloneNode(this._exprNegativo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegativoExprNegativo(this);
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PExprNegativo getExprNegativo()
    {
        return this._exprNegativo_;
    }

    public void setExprNegativo(PExprNegativo node)
    {
        if(this._exprNegativo_ != null)
        {
            this._exprNegativo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNegativo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menos_)
            + toString(this._exprNegativo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._exprNegativo_ == child)
        {
            this._exprNegativo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._exprNegativo_ == oldChild)
        {
            setExprNegativo((PExprNegativo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
