/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class ANotExprNegacao extends PExprNegacao
{
    private TNot _not_;
    private PExprNegacao _exprNegacao_;

    public ANotExprNegacao()
    {
        // Constructor
    }

    public ANotExprNegacao(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PExprNegacao _exprNegacao_)
    {
        // Constructor
        setNot(_not_);

        setExprNegacao(_exprNegacao_);

    }

    @Override
    public Object clone()
    {
        return new ANotExprNegacao(
            cloneNode(this._not_),
            cloneNode(this._exprNegacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotExprNegacao(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PExprNegacao getExprNegacao()
    {
        return this._exprNegacao_;
    }

    public void setExprNegacao(PExprNegacao node)
    {
        if(this._exprNegacao_ != null)
        {
            this._exprNegacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNegacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._exprNegacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._exprNegacao_ == child)
        {
            this._exprNegacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._exprNegacao_ == oldChild)
        {
            setExprNegacao((PExprNegacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
