/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class ASomaExprMatematica extends PExprMatematica
{
    private PExprMatematica _exprMatematica_;
    private TMais _mais_;
    private PFator _fator_;

    public ASomaExprMatematica()
    {
        // Constructor
    }

    public ASomaExprMatematica(
        @SuppressWarnings("hiding") PExprMatematica _exprMatematica_,
        @SuppressWarnings("hiding") TMais _mais_,
        @SuppressWarnings("hiding") PFator _fator_)
    {
        // Constructor
        setExprMatematica(_exprMatematica_);

        setMais(_mais_);

        setFator(_fator_);

    }

    @Override
    public Object clone()
    {
        return new ASomaExprMatematica(
            cloneNode(this._exprMatematica_),
            cloneNode(this._mais_),
            cloneNode(this._fator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomaExprMatematica(this);
    }

    public PExprMatematica getExprMatematica()
    {
        return this._exprMatematica_;
    }

    public void setExprMatematica(PExprMatematica node)
    {
        if(this._exprMatematica_ != null)
        {
            this._exprMatematica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprMatematica_ = node;
    }

    public TMais getMais()
    {
        return this._mais_;
    }

    public void setMais(TMais node)
    {
        if(this._mais_ != null)
        {
            this._mais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mais_ = node;
    }

    public PFator getFator()
    {
        return this._fator_;
    }

    public void setFator(PFator node)
    {
        if(this._fator_ != null)
        {
            this._fator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprMatematica_)
            + toString(this._mais_)
            + toString(this._fator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprMatematica_ == child)
        {
            this._exprMatematica_ = null;
            return;
        }

        if(this._mais_ == child)
        {
            this._mais_ = null;
            return;
        }

        if(this._fator_ == child)
        {
            this._fator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprMatematica_ == oldChild)
        {
            setExprMatematica((PExprMatematica) newChild);
            return;
        }

        if(this._mais_ == oldChild)
        {
            setMais((TMais) newChild);
            return;
        }

        if(this._fator_ == oldChild)
        {
            setFator((PFator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
