/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class ASymbolTipoBase extends PTipoBase
{
    private TTipoSymbol _tipoSymbol_;

    public ASymbolTipoBase()
    {
        // Constructor
    }

    public ASymbolTipoBase(
        @SuppressWarnings("hiding") TTipoSymbol _tipoSymbol_)
    {
        // Constructor
        setTipoSymbol(_tipoSymbol_);

    }

    @Override
    public Object clone()
    {
        return new ASymbolTipoBase(
            cloneNode(this._tipoSymbol_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASymbolTipoBase(this);
    }

    public TTipoSymbol getTipoSymbol()
    {
        return this._tipoSymbol_;
    }

    public void setTipoSymbol(TTipoSymbol node)
    {
        if(this._tipoSymbol_ != null)
        {
            this._tipoSymbol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoSymbol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoSymbol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoSymbol_ == child)
        {
            this._tipoSymbol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoSymbol_ == oldChild)
        {
            setTipoSymbol((TTipoSymbol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
