/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class ASymbolVectorTermo extends PTermo
{
    private TSymbolVector _symbolVector_;

    public ASymbolVectorTermo()
    {
        // Constructor
    }

    public ASymbolVectorTermo(
        @SuppressWarnings("hiding") TSymbolVector _symbolVector_)
    {
        // Constructor
        setSymbolVector(_symbolVector_);

    }

    @Override
    public Object clone()
    {
        return new ASymbolVectorTermo(
            cloneNode(this._symbolVector_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASymbolVectorTermo(this);
    }

    public TSymbolVector getSymbolVector()
    {
        return this._symbolVector_;
    }

    public void setSymbolVector(TSymbolVector node)
    {
        if(this._symbolVector_ != null)
        {
            this._symbolVector_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._symbolVector_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._symbolVector_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._symbolVector_ == child)
        {
            this._symbolVector_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._symbolVector_ == oldChild)
        {
            setSymbolVector((TSymbolVector) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
