/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AYesAnswer extends PAnswer
{
    private TYes _yes_;

    public AYesAnswer()
    {
        // Constructor
    }

    public AYesAnswer(
        @SuppressWarnings("hiding") TYes _yes_)
    {
        // Constructor
        setYes(_yes_);

    }

    @Override
    public Object clone()
    {
        return new AYesAnswer(
            cloneNode(this._yes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAYesAnswer(this);
    }

    public TYes getYes()
    {
        return this._yes_;
    }

    public void setYes(TYes node)
    {
        if(this._yes_ != null)
        {
            this._yes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._yes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._yes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._yes_ == child)
        {
            this._yes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._yes_ == oldChild)
        {
            setYes((TYes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
