/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class TAbreComentarioBloco extends Token
{
    public TAbreComentarioBloco()
    {
        super.setText("{-");
    }

    public TAbreComentarioBloco(int line, int pos)
    {
        super.setText("{-");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAbreComentarioBloco(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAbreComentarioBloco(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAbreComentarioBloco text.");
    }
}
