/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class TFechaComentarioBloco extends Token
{
    public TFechaComentarioBloco()
    {
        super.setText("-}");
    }

    public TFechaComentarioBloco(int line, int pos)
    {
        super.setText("-}");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFechaComentarioBloco(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFechaComentarioBloco(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFechaComentarioBloco text.");
    }
}
