/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class TInicioComentarioLinha extends Token
{
    public TInicioComentarioLinha()
    {
        super.setText("--");
    }

    public TInicioComentarioLinha(int line, int pos)
    {
        super.setText("--");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInicioComentarioLinha(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInicioComentarioLinha(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInicioComentarioLinha text.");
    }
}
